### ISSUE TITLE
The action passes… but nothing is written on the file

### ISSUE THREAD

**Issue by eRouge-ps** [DamianReeves/write-file-action#2]
Hey,

so I’ve managed to make this action work (very basic : go to branch, write something) : 

`name: Append File
on:  
 pull_request:
    types: [labeled, unlabeled]

jobs:
  build:
    name: Append Text
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: writefile
      - name: Write File
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{github.workspace}}/test
          contents: |
            echo "Hello World!"
          write-mode: overwrite`

The action is a success, but the file does not change at all… maybe I need to commit every thing ? I have no clue. If you have an idea I’d love to hear it !

Thanks a lot !

**Comment by Glazomer** [comment]
Did u solved it?

**Comment by leonstafford** [comment]
@eRouge-ps, please edit your issue to use \`\`\`, rather than \`, as this will format your multiline code sample properly

**Comment by DamianReeves** [comment]
> Hey,
> 
> so I’ve managed to make this action work (very basic : go to branch, write something) :
> 
> `name: Append File
> on:
> pull_request:
> types: [labeled, unlabeled]
> 
> jobs:
> build:
> name: Append Text
> runs-on: ubuntu-latest
> steps:
> - uses: actions/checkout@v2
> with:
> ref: writefile
> - name: Write File
> uses: DamianReeves/write-file-action@v1.0
> with:
> path: ${{github.workspace}}/test
> contents: |
> echo "Hello World!"
> write-mode: overwrite`
> 
> The action is a success, but the file does not change at all… maybe I need to commit every thing ? I have no clue. If you have an idea I’d love to hear it !
> 
> Thanks a lot !

So with YAML formatting matters so given what you have there its hard to debug, if you are still having an issue could you properly format the comment?

**Comment by FerhatPflegia** [comment]
I have currently the same issue. Is it solved? Mine looks like this:

``` 
name: Write commit hash and message in enviroment
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ github.workspace }}/.env
          contents: |
            echo "MESSAGE={{ github.event.head_commit.message }}"
          write-mode: append
```

**Comment by mifriis** [comment]
Hi all, 
You need to run through the process of pushing the file afterwards

```
      - run: git config --local user.email "action@github.com"
      - run: git config --local user.name "GitHub Action"
      - run: git add scores
      - run: git commit -m "file updated"
      - run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by alexandre97costa** [comment]
As the owner said, you need to commit and push the file. If you're not comfortable with running git commands, this action will do it for you:
```yaml
name: Overwrite file

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Overwrite ip.js
        uses: "DamianReeves/write-file-action@v1.0"
        with:
          path: path/to/file.js
          write-mode: overwrite
          contents: |
            some content you want to change
            
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Overwritten by Github Actions - ${date}'
```
