### ISSUE TITLE
How would you grab a output from aws cli

### ISSUE THREAD

**Issue by austinsonger** [DamianReeves/write-file-action#21]
See example below

```
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
         version: 2     # default
         verbose: false # default
         arch: amd64    # allowed values: amd64, arm64
         rootdir: ""    # defaults to "PWD"
         workdir: ""    # defaults to "PWD/unfor19-awscli"
      - run: aws acm list-certificates --output json
        shell: bash

      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: Lists/certificates.json
          write-mode: overwrite
          contents: |
            <PLACEHOLDER>
```
