### ISSUE TITLE
How to write newlines?

### ISSUE THREAD

**Issue by kevinrenskers** [DamianReeves/write-file-action#5]
I'd like to use your action to prepend generated changelog text to my CHANGELOG.md file, something like this:

```
- name: Write to CHANGELOG.md
  uses: DamianReeves/write-file-action@master
  if: ${{ !env.ACT }}
  with:
    path: ./CHANGELOG.md
    contents: ${{ steps.changelog.outputs.changelog }}${{ steps.package.outputs.content }}
    write-mode: overwrite
```

Except that I want a blank line between the new content and the existing content. I am not familiar enough with the syntax of actions and yaml.. how can add those newlines?

I tried this, but that just literally adds `echo` and `\n\n` to my file.

```
contents: |
  echo ${{ steps.changelog.outputs.changelog }}\n\n${{ steps.package.outputs.content }}
```
