### ISSUE TITLE
using variables in "content" doesn't seem to work

### ISSUE THREAD

**Issue by mifriis** [DamianReeves/write-file-action#9]
```YML
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'scores'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get commit message
        run: echo "MESSAGE=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_ENV
      - name: show commit message
        run : echo $MESSAGE
      - name: Save score
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ github.workspace }}/scores
          contents: |
            echo $MESSAGE
          write-mode: append
      # push updated file back to main branch
      - run: git config --local user.email "action@github.com"
      - run: git config --local user.name "GitHub Action"
      - run: git add scores
      - run: git commit -m "scores updated"
      - run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This action works and writes back to the repo with something. Only it's not the `message `on the current `commit` but rather `echo $MESSAGE` literally. It doesn't appear that the action executes what it recieves similar to other actions, but take the "contents" parameter literally as text.

**Comment by mifriis** [comment]
Fixed it by using `contents: ${{ env.MESSAGE }}`

like this:
```
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ github.workspace }}/scores
          contents: ${{ env.MESSAGE }}
          write-mode: append
```

documentation for this action seems to be wrong.
